vim.opt.mouse = nil
vim.opt.nu = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.backupdir = vim.env.XDG_DATA_HOME .. "/nvim/backup//"
vim.opt.backup = true
