vim.opt.autoindent = true
vim.opt.backspace = 'indent,eol,start'
vim.opt.completeopt = 'longest,menuone,preview'
vim.opt.mouse = nil
vim.opt.number = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.backupdir = vim.env.XDG_DATA_HOME .. "/nvim/backup//"
vim.opt.backup = true
